application: event_tracker
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest