
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images
- url: /imgs
  static_dir: imgs
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: /.*
  script: main.app 
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest